name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref to test
        type: string
        default: nekketsuuu-ci-test

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2"]
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.ref || github.ref }}
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Ruby Tests
      run: bundle exec rake test
    - name: RuboCop
      run: bundle exec rubocop
